version: "3.8"

services:
  app:
    build: .
    container_name: image-app
    environment:
      - APP_PORT=5000
      - FILE_SECRET=h20tavyWvchAlZko21t0X0lH93VJCQBn
    ports:
      - "5000:5000"
    restart: always